apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-external-share-manager
  labels:
    app: longhorn-external-share-manager
  namespace: longhorn-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: longhorn-external-share-manager
  labels:
    app: longhorn-external-share-manager
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  resourceNames: ["longhorn-external-share-manager"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: longhorn-external-share-manager
  labels:
    app: longhorn-external-share-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: longhorn-external-share-manager
subjects:
- kind: ServiceAccount
  name: longhorn-external-share-manager
  namespace: longhorn-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-external-share-manager
  namespace: longhorn-system
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: longhorn-external-share-manager
  template:
    metadata:
      labels:
        app: longhorn-external-share-manager
    spec:
      serviceAccountName: longhorn-external-share-manager
      containers:
      - name: longhorn-external-share-manager
        imagePullPolicy: Always
        image: ysakashita/longhorn-external-share-manager:v0.1.2
        args: ["-zap-encoder=console", "-zap-time-encoding=iso8601"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9440
          initialDelaySeconds: 10
